apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: crownlabs/frontend:stable
          imagePullPolicy: Always
          name: frontend
          securityContext:
           runAsUser: 101
           runAsGroup: 101
           privileged: false
           capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          resources:
           limits:
            memory: 100Mi
            cpu: 100m
           requests:
            memory: 100Mi
            cpu: 100m
          ports:
          - containerPort: 80
            protocol: TCP
            name: http
          env:
          - name: OIDC_PROVIDER_URL
            valueFrom:
              configMapKeyRef:
                name: frontend-env-vars
                key: oidc_provider_url
          - name: OIDC_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: frontend-env-vars
                key: oidc_client_id
          - name: OIDC_CLIENT_SECRET
            valueFrom:
              configMapKeyRef:
                name: frontend-env-vars
                key: oidc_client_secret
          - name: OIDC_REDIRECT_URI
            valueFrom:
              configMapKeyRef:
                name: frontend-env-vars
                key: oidc_redirect_uri
          - name: APISERVER_URL
            valueFrom:
              configMapKeyRef:
                name: frontend-env-vars
                key: apiserver_url
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              httpHeaders:
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred

