apiVersion: crownlabs.polito.it/v1alpha1
kind: Tenant
metadata:
  name: john.doe
  labels:
    reconcile: "true"
spec:
  firstName: John
  lastName: Doe
  email: jonh.doe@email.com
  workspaces:
    - workspaceRef:
        name: tea
      role: user
      groupNumber: 12
    - workspaceRef:
        name: coffee
      role: manager
      groupNumber: 12
  publicKeys:
    - key1
    - key2
    - key3
