apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-tenant-operator
rules:
  - apiGroups: ["crownlabs.polito.it"]
    resources: ["workspaces", "workspaces/status", "tenants", "tenants/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create", "delete"]
