---
# tasks file for xubuntu-pre

- name: Wait for any possibly running unattended-upgrade to finish
  shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 1; done;
  with_items:
    - lock
    - lock-frontend

- name: Update the apt cache
  apt:
    update_cache: yes

- name: Remove unattended-upgrades
  apt:
    name: "unattended-upgrades"
    state: absent
    autoremove: yes
    purge: yes

- name: Remove many unnecessary packages
  apt:
    name: "{{ unnecessary_packages }}"
    state: absent
    autoremove: yes
    purge: yes

- name: Upgrade all packages
  apt:
    name: "*"
    state: latest
    force_apt_get: true

- name: Make sure the Desktop directory does exist
  file:
    path: /home/{{ ansible_user }}/Desktop
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Remove useless folders from /home
  file: path=/home/{{ ansible_user }}/{{ item }} state=absent recurse=no
  with_items:
  - "Music"
  - "Pictures"
  - "Public"
  - "Templates"
  - "Videos"
