# permissions to do edit labinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labinstance-editor-role
rules:
- apiGroups:
  - instance.crownlabs.polito.it
  resources:
  - labinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - instance.crownlabs.polito.it
  resources:
  - labinstances/status
  verbs:
  - get
  - patch
  - update
