apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: nextcloud
  name: redis-nextcloud
spec:
  cluster:
    master: 1
    replicas: 3
  configSecret:
    name: redis-nextcloud
  mode: Standalone
  monitor:
    agent: prometheus.io/operator
    prometheus:
      exporter:
        port: 56790
      serviceMonitor:
        interval: 10s
        labels:
          app: kubedb
  podTemplate:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: redis-nextcloud
                  app.kubernetes.io/managed-by: kubedb.com
                  app.kubernetes.io/name: redises.kubedb.com
              namespaces:
              - nextcloud
              topologyKey: kubernetes.io/hostname
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: redis-nextcloud
                  app.kubernetes.io/managed-by: kubedb.com
                  app.kubernetes.io/name: redises.kubedb.com
              namespaces:
              - nextcloud
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 50
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
      serviceAccountName: redis-nextcloud
  replicas: 1
  serviceTemplates:
  - alias: primary
    spec:
      ports:
      - name: http
        port: 9200
      type: ClusterIP
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 250Mi
    storageClassName: rook-ceph-block
  storageType: Durable
  terminationPolicy: Halt
  version: 5.0.3-v1
