---
- hosts: all
  become: yes

  roles:
  - role: xubuntu-pre
  - role: crownlabs
    when: crownlabs_mode == True
  - role: wireshark
  - role: docker
  - role: gns3
  - role: polycube
  - role: netlab-generic
  - role: xubuntu-post
