---
# tasks file for wireshark

- name: Let non root to capture traffic
  debconf:
    name='wireshark-common'
    question='wireshark-common/install-setuid'
    vtype='boolean'
    value='true'

- name: Install the Wireshark package
  apt:
    name: "wireshark"
    state: present

- name: Add the local user to the wireshark group
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: wireshark
