apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bastion-operator.fullname" . }}-metrics
  labels:
    {{- include "bastion-operator.labels" . | nindent 4 }}
    {{- include "bastion-operator.metricsAdditionalLabels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 5s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "bastion-operator.selectorLabels" . | nindent 6 }}
      {{- include "bastion-operator.metricsAdditionalLabels" . | nindent 6 }}
