apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "instance-operator.fullname" . }}
  labels:
    {{- include "instance-operator.labels" . | nindent 4 }}
data:
  nextcloud-base-url: {{ .Values.configurations.nextcloud.baseUrl }}
  oauth2-proxy-image: {{ .Values.configurations.generic.oauth2ProxyImage }}
  oidc-client-id: {{ .Values.configurations.oidc.clientId }}
  oidc-client-secret: {{ .Values.configurations.oidc.clientSecret }}
  oidc-provider-url: {{ .Values.configurations.oidc.providerUrl }}
  webdav-secret-name: {{ .Values.configurations.nextcloud.webdavSecretName }}
  website-base-url: {{ .Values.configurations.generic.websiteBaseUri }}
  whitelist-labels: {{ .Values.configurations.generic.whitelistLabels }}
