apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbacResourcesName }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
rules:
- apiGroups: ["crownlabs.polito.it"]
  resources: ["workspaces", "workspaces/status", "tenants", "tenants/status", "instances", "instances/status", "templates", "templates/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]

- apiGroups: [""]
  resources: ["namespaces", "resourcequotas", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "deletecollection"]

- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "deletecollection"]

- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "deletecollection"]
