# Default values for frontend-storybook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: crownlabs/frontend-storybook
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deploymentAnnotations: {}
podAnnotations: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  privileged: false

service:
  type: ClusterIP
  port: 80

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hostname: crownlabs.example.com
  path: /
  secret: frontend-storybook-certificate

resources:
  limits:
    cpu: 100m
    memory: 250Mi
  requests:
    cpu: 10m
    memory: 25Mi
