apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: crownlabsinstancetemplatereference
  namespace: "gatekeeper-system"
  labels:
     policy: verify-instance-template-reference
spec:
  sync:
    syncOnly:
      - group: "crownlabs.polito.it"
        version: "v1alpha2"
        kind: "Template"