{{- define "policies.sync" -}}
{{- $sync := list }}
{{- range .Values.policies }}
{{- if .sync }}
{{- $sync = concat $sync .sync }}
{{- end -}}
{{- end -}}
{{ toYaml ( $sync | uniq ) }}
{{- end -}}

apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  # The name must be config, otherwise it is not reconciled by gatekeeper
  # https://github.com/open-policy-agent/gatekeeper#replicating-data
  name: config
  namespace: {{ .Values.gatekeeperNamespace }}
  labels:
    {{- include "policies.labels" . | nindent 4 }}
spec:
  sync:
    syncOnly:
      {{- ( include "policies.sync" . ) | nindent 6 }}
