{{- range .Values.policies }}
---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: {{ lower .name }}
  labels:
    {{- include "policies.labels" $ | nindent 4 }}
spec:
  crd:
    spec:
      names:
        kind: {{ .name }}
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |-
      {{- $.Files.Get .file | nindent 6 }}
{{- end }}
