apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qlkube.fullname" . }}
  labels:
    {{- include "qlkube.labels" . | nindent 4 }}
data:
  {{ .Values.configuration.exposedAPIs.fileName }}: |
    const apiGroups = {
      paths: [
        {{- range .Values.configuration.exposedAPIs.apis }}
          '{{ . }}',
        {{- end }}
      ],
    };

    module.exports = { apiGroups };

  {{ .Values.configuration.subscriptions.fileName }}: |
    const subscriptions = [
      {{- range $api := .Values.configuration.subscriptions.apis }}
      {{- range .resources }}
      {
        api: 'apis',
        group: '{{ $api.group }}',
        version: '{{ .version }}',
        resource: '{{ .resource }}',
        type: '{{ .mapping }}',
      },
      {{- end }}
      {{- end }}
    ];

    module.exports = { subscriptions };
