---
# tasks file for netlab-generic

- name: Install the packages required for the sniffing lab
  apt:
    name: "{{ to_install }}"
    state: present
  vars:
    to_install:
    - build-essential
    - cmake
    - libpcap-dev

- name: Install the Open vSwitch packages
  apt:
    name: "{{ to_install }}"
    state: present
  vars:
    to_install:
    - openvswitch-switch
