---

# tasks for codeblocks
# adds the ppa repository, since the packets available in the default repositories of ubuntu < 20.04 are outdated
# original instructions here: http://ubuntuhandbook.org/index.php/2020/03/install-codeblocks-20-03-ubuntu-18-04/

- name: Add codeblocks APT repository
  apt_repository:
    repo: deb http://ppa.launchpad.net/codeblocks-devs/release/ubuntu {{ansible_distribution_release}} main
  when: ansible_distribution_major_version < '20'

- name: Install the codeblocks packages
  apt:
    name: "{{ to_install }}"
    state: present
  vars:
    to_install:
    - codeblocks
    - codeblocks-contrib
