---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: imagelists.crownlabs.polito.it
spec:
  group: crownlabs.polito.it
  names:
    kind: ImageList
    listKind: ImageListList
    plural: imagelists
    singular: imagelist
  scope: Cluster
  validation:
    openAPIV3Schema:
      description: ImageList is the Schema for the imagelists API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info:
            https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info:
            https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: 'ImageListSpec defines the desired state of ImageList'
          properties:
            registryName:
              description: 'The host name that can be used to access the registry'
              type: string
            images:
              description: 'The list of VM images currently available for crownlabs'
              items:
                properties:
                  name:
                    description: 'The name identifying a single image'
                    type: string
                  versions:
                    description: 'The list of versions the image is available in'
                    items:
                      type: string
                    type: array
                required:
                - name
                - versions
                type: object
              type: array
          required:
          - registryName
          - images
          type: object
        status:
          description: 'ImageListStatus defines the observed state of ImageList'
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
