# Default values for policies.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Include here the policies that need to be deployed with the helm chart
### Name is the name of the policy
### File is the path of the rego rule implementing the policy
### DryRun decides whether the policy is enforced or not
### Resources is the list of kinds the policy applies to
### Sync is the list of resources that need to be accessed from the policy
policies:

  # This policy verifies that an instance refers to an existing template
  # in the correct namespace when it is created or updated.
  - name: CrownLabsInstanceTemplateReference
    file: policies/instance-template-reference.rego
    dryRun: true
    resources:
      - apiGroups:
        - crownlabs.polito.it
        kinds:
        - Instance
    sync:
      - group: "crownlabs.polito.it"
        version: "v1alpha2"
        kind: "Template"

  # This policy verifies that a tenant creation or patch is allowed.
  - name: CrownLabsTenantPatch
    file: policies/tenant-patch.rego
    dryRun: true
    resources:
      - apiGroups:
        - crownlabs.polito.it
        kinds:
        - Tenant
    sync:
      - group: "crownlabs.polito.it"
        version: "v1alpha1"
        kind: "Tenant"

# The namespace where gatekeeper is installed
gatekeeperNamespace: gatekeeper-system

# Hook configurations
hook:
  kubectlImage: bitnami/kubectl:1.21
  pullPolicy: IfNotPresent
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    privileged: false
  resources:
    limits:
      memory: 250Mi
      cpu: 1000m
    requests:
      memory: 250Mi
      cpu: 10m

nameOverride: ""
fullNameOverride: ""
