apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: keycloak-certificate
  namespace: keycloak-ha
spec:
  secretName: keycloak-certificate-secret
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
  - auth.crownlabs.polito.it
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
