name: Check Markdown links

on:
  push:
    branches-ignore:
    - master
    tags-ignore:
    - "**"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check the validity of the links in the documentation
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
