name: Go
on:
  push:
    tags:
    - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.CI_TOKEN }}

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build and Push Laboratory-Operator image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crownlabs/laboratory-operator
        username: ${{ secrets.DOCKER_USERNAME }}
        dockerfile: Dockerfile
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: operators/labInstance-operator/
        tags: "latest,stable,${{ steps.get_version.outputs.VERSION }}"

    - name: Build and Push Frontend image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: crownlabs/frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        dockerfile: Dockerfile
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: webservice
        tags: "latest,stable,${{ steps.get_version.outputs.VERSION }}"

