name: Release a new CrownLabs version
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Get the CrownLabs version to be released
        id: version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - name: Get the latest CrownLabs release
        uses: pozetroninc/github-action-get-latest-release@v0.5.0
        id: last-release
        with:
          repository: ${{ github.repository }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push the Frontend image
        uses: docker/build-push-action@v2
        with:
          tags: |
            crownlabs/website:latest
            crownlabs/website:stable
            crownlabs/website:${{ steps.version.outputs.version }}
          push: true
          file: ./webservice/Dockerfile
          context: ./webservice

      - name: Build and Push the Laboratory operator image
        uses: docker/build-push-action@v2
        with:
          tags: |
            crownlabs/laboratory-operator:latest
            crownlabs/laboratory-operator:stable
            crownlabs/laboratory-operator:${{ steps.version.outputs.version }}
          push: true
          file: ./operators/labInstance-operator/Dockerfile
          context: ./operators/labInstance-operator/

      - name: Generate the CHANGELOG
        uses: RiskLedger/generate-changelog@v1.2
        id: changelog
        with:
          from: ${{ steps.last-release.outputs.release }}
          to: ${{ steps.version.outputs.version }}
        env:
          GITHUB_AUTH: ${{ secrets.CI_TOKEN }}

      - name: Save the CHANGELOG as a file
        run: |
          echo "${{ steps.changelog.outputs.changelog }}" > ./CHANGELOG.md
          sed -i "1s/.*/## Changes since ${{ steps.last-release.outputs.release }}/" ./CHANGELOG.md

      - name: Create the release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body_path: ./CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Notify Event to CrownOps
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CI_TOKEN }}
          repository: netgroup-polito/CrownOps
          event-type: release-event
          client_payload: '{"version": "${{ steps.version.outputs.version }}"}'
