name: Check linting in webservice
on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - "**"
jobs:
  webservice_lint_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code in action environment
        uses: actions/checkout@v2
      - name: collect data about changes in path
        uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          filters: |
            webservice:
              - 'webservice/**/*'
      - name: setup nodeJS in action environment
        if: steps.filter.outputs.webservice == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install necessary packages for lint checking
        if: steps.filter.outputs.webservice == 'true'
        working-directory: ./webservice
        run: npm run lint-setup
      - name: run npm script to check linting
        if: steps.filter.outputs.webservice == 'true'
        working-directory: ./webservice
        run: npm run lint-check
