apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labtemplate-consumer-operator
rules:
  - apiGroups:
      - template.crownlabs.polito.it
    resources:
      - labtemplates
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: labinstance-consumer-operator
rules:
  - apiGroups:
      - instance.crownlabs.polito.it
    resources:
      - labinstances
    verbs:
      - get
      - create
      - update
      - list
      - patch
      - deletecollection
      - watch
      - delete

